# yamllint disable rule:line-length
# SPDX-License-Identifier: AGPL-3.0+
#
# Copyright (C) 2019 Ultimaker B.V.

include:
  - project: ultimaker/embedded/prime-jedi
    ref: master-S1
    file: /gitlab_ci_templates/S1-gitlab-ci-template.yml
